#!/usr/bin/with-contenv sh
# shellcheck shell=sh
# shellcheck enable=require-variable-braces

apk --update --no-cache upgrade >/dev/null
apk cache clean 2>/dev/null || true

update-ca-certificates >/dev/null

pure_ftpd_ver_on="$(curl -sSfL 'https://download.pureftpd.org/pub/pure-ftpd/releases/' | \
                    sed -n 's%.*href=\"pure-ftpd-\([0-9\.-]*\)\.tar.gz.*%\1%p' | sort -Vr | head -n1)"
pure_ftpd_ver_of="$(pure-ftpd -h 2>&1 | sed -n 's/^pure-ftpd v\([0-9\.-]*\) .*/\1/p')"

if [ "${pure_ftpd_ver_of}" != "${pure_ftpd_ver_on}" ]; then
  apk --update --no-cache add \
    && apk add --no-cache --virtual .tool-deps \
    coreutils autoconf g++ libtool make \
    && apk add --no-cache --virtual .build-deps \
    libretls-dev libsodium-dev \
    && curl -sSfL -o "/tmp/pure-ftpd.tar.gz" \
      "https://download.pureftpd.org/pub/pure-ftpd/releases/pure-ftpd-${pure_ftpd_ver_on}.tar.gz" \
    && tar -xzf "/tmp/pure-ftpd.tar.gz" -C /tmp/ \
    && cd "/tmp/pure-ftpd-${pure_ftpd_ver_on}" \
    && ./configure \
      --prefix=/usr \
      --with-altlog \
      --with-ftpwho \
      --with-puredb \
      --with-peruserlimits \
      --with-rfc2640 \
      --without-capabilities \
      --without-humor \
      --without-inetd \
      --without-pam \
      --without-shadow \
      --without-usernames \
    && make -j2 && make -j2 install \
    && apk del .tool-deps .build-deps; \
    apk cache clean; \
    rm -rf /etc/periodic /tmp/* /usr/share/man/* /var/cache/apk/* /etc/socklog.rules/*
fi
